# Generated by Django 5.1.4 on 2024-12-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('accno', models.IntegerField(primary_key='accno', serialize=False)),
                ('ifscno', models.IntegerField()),
                ('mobno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
